"""Action Agent: single-call slot extraction + tool dispatch.

Design choices that matter for cost: (1) one LLM call decides both which
tool applies and extracts its arguments — no separate "which tool" and
"which arguments" round trips; (2) the employee_id is injected from the
authenticated session state, never asked of the model or the user; (3) the
final user-facing message for a successful tool call is templated in
Python, not generated by another LLM call.
"""
from __future__ import annotations

import json
import time

from src import config
from src.graph.state import HCMState
from src.llm.gemini_client import get_client
from src.observability.tracer import Tracer
from src.tools.executor import execute_tool
from src.tools.schemas import ALL_TOOL_SCHEMAS

TOOL_REQUIRED_FIELDS = {
    "check_leave_balance": ["leave_type"],
    "apply_leave": ["leave_type", "start_date", "num_days"],
    "get_payslip": ["month"],
}

EXTRACTION_SCHEMA = {
    "type": "object",
    "properties": {
        "tool_name": {
            "type": "string",
            "enum": ["check_leave_balance", "apply_leave", "get_payslip"],
        },
        "arguments": {
            "type": "object",
            "properties": {
                "leave_type": {
                    "type": "string",
                    "enum": ["earned_leave", "casual_leave", "sick_leave"],
                },
                "start_date": {"type": "string", "description": "YYYY-MM-DD"},
                "num_days": {"type": "integer"},
                "reason": {"type": "string"},
                "month": {"type": "string", "description": "YYYY-MM"},
            },
        },
        "missing_fields": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["tool_name", "arguments", "missing_fields"],
}

EXTRACTION_SYSTEM_PROMPT = (
    "You are the argument-extraction step for an HR Action Agent. Available tools "
    "(employee_id is supplied separately by the system, never ask for it):\n"
    f"{json.dumps(ALL_TOOL_SCHEMAS, indent=2)}\n\n"
    "Given the recent conversation and the latest employee message, decide which tool "
    "applies and extract as many arguments as you can. Normalize dates to YYYY-MM-DD "
    "and months to YYYY-MM; if no year is stated, assume 2026. List any still-missing "
    'REQUIRED argument (other than employee_id) in "missing_fields". Respond with ONLY '
    "the JSON object, no other text."
)

FIELD_PROMPTS = {
    "leave_type": "which leave type (earned, casual, or sick leave)",
    "start_date": "the start date (YYYY-MM-DD)",
    "num_days": "how many days",
    "month": "which month (YYYY-MM)",
}


def _format_tool_response(tool_name: str, output: dict, success: bool) -> str:
    if not success:
        return output["message"]
    if tool_name == "check_leave_balance":
        leave_label = output["leave_type"].replace("_", " ")
        return f"You have {output['available_days']} day(s) of {leave_label} available."
    if tool_name == "apply_leave":
        return output["message"]
    if tool_name == "get_payslip":
        b = output["breakdown"]
        return (
            f"Payslip for {output['month']}: gross pay {b['gross_pay']}, "
            f"deductions {b['deductions']['total']}, net pay {b['net_pay']}."
        )
    return json.dumps(output)


def _clarifying_question(tool_name: str | None, missing_fields: list[str]) -> str:
    if not tool_name:
        return (
            "Could you clarify what HR action you'd like to take — checking your "
            "leave balance, applying for leave, or fetching a payslip?"
        )
    asks = [FIELD_PROMPTS.get(f, f) for f in missing_fields] or ["a few more details"]
    return "To proceed, could you tell me " + " and ".join(asks) + "?"


def handle_action(state: HCMState, tracer: Tracer) -> dict:
    start = time.perf_counter()
    user_input = state["user_input"]
    pending = state.get("pending_action") or {}
    tool_name = pending.get("tool_name")
    arguments = dict(pending.get("arguments") or {})

    client = get_client()
    recent_history = state["history"][-6:]
    history_text = "\n".join(f"{t['role']}: {t['content']}" for t in recent_history)
    prompt = f"Conversation so far:\n{history_text}\n\nLatest message: {user_input}"
    if tool_name:
        prompt += (
            f"\n\nAlready decided tool: {tool_name}\n"
            f"Already known arguments: {json.dumps(arguments)}"
        )

    gen_result = client.generate(
        model=config.FLASH_MODEL,
        system_instruction=EXTRACTION_SYSTEM_PROMPT,
        prompt=prompt,
        response_schema=EXTRACTION_SCHEMA,
        temperature=0.0,
    )

    try:
        parsed = gen_result.parsed or json.loads(gen_result.text)
        tool_name = parsed.get("tool_name") or tool_name
        extracted = {
            k: v for k, v in (parsed.get("arguments") or {}).items() if v not in (None, "")
        }
        arguments.update(extracted)
    except (ValueError, TypeError, AttributeError):
        pass

    required = TOOL_REQUIRED_FIELDS.get(tool_name, [])
    still_missing = [f for f in required if not arguments.get(f)]

    if not tool_name or still_missing:
        clarifying = _clarifying_question(tool_name, still_missing)
        latency_ms = (time.perf_counter() - start) * 1000
        tracer.log_step(
            turn_id=state["turn_id"],
            agent_name="action_agent",
            input={"user_input": user_input, "tool_name": tool_name},
            output={"response": clarifying, "missing_fields": still_missing},
            latency_ms=latency_ms,
            tokens_in=gen_result.tokens_in,
            tokens_out=gen_result.tokens_out,
            cost_usd=gen_result.cost_usd,
            model=gen_result.model,
        )
        return {
            "final_response": clarifying,
            "pending_action": {
                "tool_name": tool_name,
                "arguments": arguments,
                "missing_fields": still_missing,
            },
            "history": [{"role": "assistant", "content": clarifying, "agent": "action_agent"}],
        }

    dispatch_args = dict(arguments)
    dispatch_args["employee_id"] = state["employee_id"]
    tool_result = execute_tool(tool_name, dispatch_args)
    response_text = _format_tool_response(tool_name, tool_result.output, tool_result.success)

    latency_ms = (time.perf_counter() - start) * 1000
    tracer.log_step(
        turn_id=state["turn_id"],
        agent_name="action_agent",
        input={"user_input": user_input, "tool_name": tool_name, "arguments": dispatch_args},
        output={"response": response_text},
        tool_calls=[
            {
                "tool_name": tool_result.tool_name,
                "arguments": tool_result.arguments,
                "output": tool_result.output,
                "success": tool_result.success,
                "attempts": tool_result.attempts,
                "latency_ms": tool_result.latency_ms,
            }
        ],
        latency_ms=latency_ms,
        tokens_in=gen_result.tokens_in,
        tokens_out=gen_result.tokens_out,
        cost_usd=gen_result.cost_usd,
        model=gen_result.model,
    )

    return {
        "final_response": response_text,
        "pending_action": None,
        "history": [{"role": "assistant", "content": response_text, "agent": "action_agent"}],
    }
